### ISSUE TITLE
About faiss

### ISSUE THREAD

**Issue by zjh-nudger** [bakercp/ofxFAISS#1]
Hi, I am quite interest on faiss, a large-scale similarity search framework. However, I am not familier with C/C++. I want to know whether faiss can be packaged into Java interface for being utilized in Java application. 

look forward to you reply. 
Best regards.

**Comment by bakercp** [comment]
Yes, it could be via a JNI (Java Native Interface) layer, but this is something that should be discussed on the main repository.  This is a wrapper for openFrameworks, which is C++. http://github.com/facebookresearch/faiss/
